# if you have correctly installed rising-registry
# using pip install rising-registry
from registry import Registry, ID

# An ID must have an integer to use, but can optionally store a value
Z = ID(0) # Z.ID = 0, Z.VALUE = None

# a registry is an object for managing ID's
# it can be created in two ways

# 1). context manager
# this way makes the registry more private, by sealing it after it is done
with Registry(name="MY_NUMS", step=1) as auto: # name and step are optional
    # you can insert a value and id manually or leave both blank
    X = auto("hi", "hi") # X.VALUE = None, if ID is None X.ID is automatically generated by the registry starting at 0
    
    # if you set an ID as one that is already in the registry
    # it will use the same ID object, but change its value
    Y = auto("example_value", 0) # _ means X and Y; _.VALUE = "example_value", _.ID = 0
# if you were to use auto here it would raise an error

# 2). manually
registry = Registry(step = 2) # create a Registry object
# the registry is unsealed by default and can be used just as before
A = registry.register() # A.VALUE = None, A.ID = 0
B = registry.register("example_value") # A.VALUE = None, A.ID = 2
C = registry.register()

# the registry can be sealed and unsealed manually as well
registry.seal()

# D = registry.register() # will raise an error

# registry.unseal() # unseal the registry
# registry.toggle_seal() # to flip the registries seal state


# comparison of ID's

print(Y == A) # -> True, because both ID objects have the sane id
print(B > Y) # -> True, because B's id is greater than Y's
print(Y is X) # -> True, because both objects are the same object
print(Y & A) # -> True, because both have the same value
print(A & C) # -> False, because although both have the same value it is None